<?php

/**
 * @file
 * Contains marketo_js.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function marketo_js_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the marketo_js module.
    case 'help.page.marketo_js':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Marketo JS form integration, functionality.') . '</p>';
      return $output;

    default:
  }
}