<?php

/**
 * @file
 * Defines Marketo Form field type.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function marketo_form_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'marketo_form.page.link':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>Marketo Form integration</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function marketo_form_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__marketo_form' => [
      'template' => 'paragraph',
      'base hook' => 'paragraph',
      'path' => drupal_get_path('module', 'parade') . '/templates',
    ],
    'marketo_form_field' => [
      'variables' => [
        'forms' => NULL,
        'entity' => NULL,
      ],
    ],
  ];
}
