<?php

/**
 * @file
 * Code for Parade Demo.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Utility\Html;

/**
 * Implements hook_theme().
 */
function parade_demo_theme($existing, $type, $theme, $path) {
  return [
    'page__node__parade_demo' => [],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function parade_demo_page_attachments(array &$page) {
  $attributes = Drupal::request()->attributes;
  if ($attributes->has('node') && $attributes->get('node')->getType() == 'parade_demo') {
    $page['#attached']['library'][] = 'parade_demo/parade_demo';
  }
}

/**
 * Implements hook_form_alter().
 *
 * @todo Use more specific hook.
 */
function parade_demo_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (in_array($form_id, ['node_parade_demo_form', 'node_parade_demo_edit_form'])) {
    $form['field_menu']['widget']['add_more']['#value'] = t('Add menu link');

    // Modify the Paragraphs field.
    if (isset($form['field_parade_demo'])) {
      $form['#attached']['library'][] = 'parade/buttons';

      foreach ($form['field_parade_demo']['widget']['add_more'] as $key => $item) {
        if (strpos($key, 'add_more') === FALSE) {
          continue;
        }
        $type = Html::getClass($item['#bundle_machine_name']);
        $form['field_parade_demo']['widget']['add_more'][$key]['#attributes']['class'][] = 'parade-button';
        $form['field_parade_demo']['widget']['add_more'][$key]['#attributes']['class'][] = 'parade-button-' . $type;
      }
    }
  }
}

/**
 * Implements hook_field_widget_form_alter().
 */
function parade_demo_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  // @fixme check for field Type, not name.
  // @todo also check for Parade content type!
  $field_name = $context['items']->getFieldDefinition()->getName();

  // Change dropbuttons to normal list in Paragraphs inline forms.
  if ($field_name === 'field_parade_demo') {
    unset($element['top']['links']['#theme_wrappers']);
    $element['top']['links']['prefix']['#markup'] = '<ul class="parade-actions">';
  }

  // Changes to Menu field.
  if ($field_name === 'field_menu') {
    $element['uri']['#description'] = NULL;
    $element['uri']['#title_display'] = 'none';
    $element['title']['#title_display'] = 'none';
  }
}
