<?php

/**
 * @file
 * Contains campaign_pages.module
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function campaign_pages_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the campain_pages module.
    case 'help.page.campain_pages':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Campain pages functionality') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function campaign_pages_page_attachments_alter(array &$attachments) {
  $attributes = \Drupal::request()->attributes;
  if ($attributes->get('_entity_form') !== "node.edit" && $node = $attributes->get('node')) {
    if ($machine_name = $node->get('field_machine_name')->value) {
      $css_file_name = \Drupal::theme()->getActiveTheme()->getPath() . '/css/campaign/' . $machine_name . '.css';
      if (file_exists($css_file_name)) {
        $attachments['#attached']['html_head'][] = [
          // The data.
          [
            '#type' => 'html_tag',
            '#tag' => 'style',
            '#value' => '@import url("/' . $css_file_name . '");',
            '#attributes' => array('media' => 'all'),
            '#weight' => 1000,

          ],
          'campaign_pages_css'
        ];
      }
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Add field_title_class value as class to field_title.
 */
function campaign_pages_preprocess_field(&$variables) {
  if ($variables['element']['#field_name'] === 'field_title' && isset($variables['element']['#object']->field_title_class)) {
    if ($class = $variables['element']['#object']->field_title_class->getValue()[0]['value']) {
      $variables['attributes']['class'][] = $class;
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Add field_paragraph_class value as class to paragraph.
 */
function campaign_pages_preprocess_paragraph(&$variables) {
  if (isset($variables['paragraph']->field_paragraph_class)) {
    if ($class = $variables['paragraph']->field_paragraph_class->getValue()[0]['value']) {
      $variables['attributes']['class'][] = $class;
    }
  }
}
